/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { L2Destination__factory } from "./L2Destination__factory";
export { L2Source__factory } from "./L2Source__factory";
