/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { L2Destination } from "./L2Destination";
export type { L2Source } from "./L2Source";
export * as factories from "./factories";
export { L2Destination__factory } from "./factories/L2Destination__factory";
export { L2Source__factory } from "./factories/L2Source__factory";
